<a href="https://colab.research.google.com/github/Thorne-Musau/np/blob/main/Broadcasting_in_NpArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

In [1]:
import numpy as np
a = np.array([0,1,1])
b = np.array([5,5,5])
a + b

array([5, 6, 6])

Broadcasting helps to allow these types of operations to be performed on arrays
This includes adding a scalar to a numpy array

In [4]:
# Such that the result can be as follows
a + 7
# Adding the scalar to each element of the array

array([7, 8, 8])

In [9]:
# can also be used in multile dimensional arrays
N = np.ones((3,3))
N

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
N + a

array([[1., 2., 2.],
       [1., 2., 2.],
       [1., 2., 2.]])

In [16]:
# More complex cases:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [17]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# **Rules of Broadcasting**
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

> * Rule 1: If the two arrays differ in their
number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


In [19]:
# Example 1
m= np.ones((2,3))
a = np.arange(3)
print(a)


[0 1 2]


In [21]:
m + a
# We see that array a has fewer dimensions in regards to the second one
# so we stretch the second one to match

array([[1., 2., 3.],
       [1., 2., 3.]])