<a href="https://colab.research.google.com/github/Thorne-Musau/np/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy importation into the workbook
import pandas as pd
import numpy as np
# Random number generator
rng = np.random.default_rng(seed=1701) # Seeding for reproductibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array
print(x1)

In [ ]:
# Array attributes
# ndim -Number of dimensions
# shape - size of each dimension
# size- total size of the array
# dtype - type of each element
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

In [ ]:
# Numpy array indexing similar to python (Starting from zero to i-th value)
x1
x1[0] # First value
x1[-1] # Last value in array

In [ ]:
# Multidemensional arrays (comma separated [rows,columns])
x2[0,0]

In [ ]:
# Modifying values
x2[0,0] =12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [ ]:
# Array slicing
# 1d arrays
# x[start:stop:step]
# A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array
x1[:3]  # first three elements
x1[3:]  # elements after index 3

array([3, 8, 6])

In [ ]:
x1[1::2]  # every second element, starting at index 1

array([4, 3, 6])

In [ ]:
# Multidemensional arrays
x2[:2, :3]  # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [ ]:
x2[::-1, ::-1]  # all rows & columns, reversed
# step value being negative, the array is reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [ ]:
# Subarrays as No-Copy Views
# Changes made to sub arrays are directly reflected on the main numpy array unlike in python slicing
x2_sub = x2[:2, :2]
x2_sub[0,0]= 22
print(x2)

[[22  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
# Reshaping arrays
# The use of .reshape fn
x = np.array([1, 2, 3])
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [ ]:
# If reshaping into one row or column, the np.newaxis is used
x[:, np.newaxis ] #  Arranging in column axis

array([[1],
       [2],
       [3]])

In [ ]:
# Concatenation of Arrays
# np.concatenate, np.vstack, and np.hstack. np.concatenate are used in joining
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
# concatenate more than two arrays at once:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
# In 2D- Arrays
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid], axis =1) # zero indexed axis

In [ ]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [ ]:
# Splitting arrays
#  implemented by the functions np.split, np.hsplit, and np.vsplit
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
# grid = np.arange(16).reshape((4, 4))

# upper, lower = np.vsplit(grid, [2])
# print(upper)
# print(lower)

# left, right = np.hsplit(grid, [2])
# print(left)
# print(right)