<a href="https://colab.research.google.com/github/Thorne-Musau/np/blob/main/U_funcs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Conventional python looping takes time when observed with %timeit
import numpy as np
np.random.seed(0)
def compute(values):
  output = np.empty(len(values))

  for i in range (len(values)):
    output[i]= 1.0 /values[i]
  return output
values = np.random.randint(1,100,size=5)
big_data= np.random.randint(1,100, size= 100000)
%timeit compute(big_data)

197 ms ± 34.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# Ufunc of numpy is faster than the python loop
%timeit 1.0 /values
%timeit 1.0 / big_data

1.51 µs ± 366 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
179 µs ± 29.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Exploring NumPy's UFuncs
## Array arithmetics- makes use of the standard addition and subtraction
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
# There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [ ]:
# Can be wound together
-(0.5*x+1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
x

array([0, 1, 2, 3])

In [ ]:
np.add(x,2)

array([2, 3, 4, 5])

In [ ]:
# Operator	Equivalent ufunc	Description
# +	np.add	Addition (e.g., 1 + 1 = 2)
# -	np.subtract	Subtraction (e.g., 3 - 2 = 1)
# -	np.negative	Unary negation (e.g., -2)
# *	np.multiply	Multiplication (e.g., 2 * 3 = 6)
# /	np.divide	Division (e.g., 3 / 2 = 1.5)
# //	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
# **	np.power	Exponentiation (e.g., 2 ** 3 = 8)
# %	np.mod- Modulus or reminder

In [ ]:
## Absolute value U-func
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
# Corresponding U-Func to this is the np.absolute function also abs
np.absolute(x)

array([2, 1, 0, 1, 2])

In [ ]:
# Can also handle complex data
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
## Trigonometric Functions
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))